var group__group__vision__functions =
[
    [ "Absolute Difference", "dc/ddf/group__group__vision__function__absdiff.html", "dc/ddf/group__group__vision__function__absdiff" ],
    [ "Accumulate", "d0/d77/group__group__vision__function__accumulate.html", "d0/d77/group__group__vision__function__accumulate" ],
    [ "Accumulate Squared", "d0/d2c/group__group__vision__function__accumulate__square.html", "d0/d2c/group__group__vision__function__accumulate__square" ],
    [ "Accumulate Weighted", "d2/d2e/group__group__vision__function__accumulate__weighted.html", "d2/d2e/group__group__vision__function__accumulate__weighted" ],
    [ "Arithmetic Addition", "d6/db0/group__group__vision__function__add.html", "d6/db0/group__group__vision__function__add" ],
    [ "Arithmetic Subtraction", "d6/d6d/group__group__vision__function__sub.html", "d6/d6d/group__group__vision__function__sub" ],
    [ "Bitwise AND", "d4/d4e/group__group__vision__function__and.html", "d4/d4e/group__group__vision__function__and" ],
    [ "Bitwise EXCLUSIVE OR", "d3/dd1/group__group__vision__function__xor.html", "d3/dd1/group__group__vision__function__xor" ],
    [ "Bitwise INCLUSIVE OR", "d2/d5d/group__group__vision__function__or.html", "d2/d5d/group__group__vision__function__or" ],
    [ "Bitwise NOT", "dc/d06/group__group__vision__function__not.html", "dc/d06/group__group__vision__function__not" ],
    [ "Box Filter", "da/d7c/group__group__vision__function__box__image.html", "da/d7c/group__group__vision__function__box__image" ],
    [ "Canny Edge Detector", "d7/d71/group__group__vision__function__canny.html", "d7/d71/group__group__vision__function__canny" ],
    [ "Channel Combine", "de/df2/group__group__vision__function__channelcombine.html", "de/df2/group__group__vision__function__channelcombine" ],
    [ "Channel Extract", "dd/dc1/group__group__vision__function__channelextract.html", "dd/dc1/group__group__vision__function__channelextract" ],
    [ "Color Convert", "d1/dc2/group__group__vision__function__colorconvert.html", "d1/dc2/group__group__vision__function__colorconvert" ],
    [ "Convert Bit depth", "de/d73/group__group__vision__function__convertdepth.html", "de/d73/group__group__vision__function__convertdepth" ],
    [ "Custom Convolution", "d3/d3b/group__group__vision__function__custom__convolution.html", "d3/d3b/group__group__vision__function__custom__convolution" ],
    [ "Dilate Image", "dc/d73/group__group__vision__function__dilate__image.html", "dc/d73/group__group__vision__function__dilate__image" ],
    [ "Equalize Histogram", "d1/d70/group__group__vision__function__equalize__hist.html", "d1/d70/group__group__vision__function__equalize__hist" ],
    [ "Erode Image", "dc/dff/group__group__vision__function__erode__image.html", "dc/dff/group__group__vision__function__erode__image" ],
    [ "Fast Corners", "dd/d22/group__group__vision__function__fast.html", "dd/d22/group__group__vision__function__fast" ],
    [ "Gaussian Filter", "d6/d58/group__group__vision__function__gaussian__image.html", "d6/d58/group__group__vision__function__gaussian__image" ],
    [ "Harris Corners", "d7/d5f/group__group__vision__function__harris.html", "d7/d5f/group__group__vision__function__harris" ],
    [ "Histogram", "d6/dcb/group__group__vision__function__histogram.html", "d6/dcb/group__group__vision__function__histogram" ],
    [ "Gaussian Image Pyramid", "d0/d15/group__group__vision__function__gaussian__pyramid.html", "d0/d15/group__group__vision__function__gaussian__pyramid" ],
    [ "Integral Image", "d0/d7b/group__group__vision__function__integral__image.html", "d0/d7b/group__group__vision__function__integral__image" ],
    [ "Magnitude", "dd/df2/group__group__vision__function__magnitude.html", "dd/df2/group__group__vision__function__magnitude" ],
    [ "Mean and Standard Deviation", "d8/d85/group__group__vision__function__meanstddev.html", "d8/d85/group__group__vision__function__meanstddev" ],
    [ "Median Filter", "d3/d77/group__group__vision__function__median__image.html", "d3/d77/group__group__vision__function__median__image" ],
    [ "Min, Max Location", "d8/d05/group__group__vision__function__minmaxloc.html", "d8/d05/group__group__vision__function__minmaxloc" ],
    [ "Optical Flow Pyramid (LK)", "d0/d0c/group__group__vision__function__opticalflowpyrlk.html", "d0/d0c/group__group__vision__function__opticalflowpyrlk" ],
    [ "Phase", "db/d4e/group__group__vision__function__phase.html", "db/d4e/group__group__vision__function__phase" ],
    [ "Pixel-wise Multiplication", "d7/dae/group__group__vision__function__mult.html", "d7/dae/group__group__vision__function__mult" ],
    [ "Remap", "df/dca/group__group__vision__function__remap.html", "df/dca/group__group__vision__function__remap" ],
    [ "Scale Image", "d1/d26/group__group__vision__function__scale__image.html", "d1/d26/group__group__vision__function__scale__image" ],
    [ "Sobel 3x3", "da/d4b/group__group__vision__function__sobel3x3.html", "da/d4b/group__group__vision__function__sobel3x3" ],
    [ "TableLookup", "d5/d4e/group__group__vision__function__lut.html", "d5/d4e/group__group__vision__function__lut" ],
    [ "Thresholding", "d3/d1e/group__group__vision__function__threshold.html", "d3/d1e/group__group__vision__function__threshold" ],
    [ "Warp Affine", "d5/d5f/group__group__vision__function__warp__affine.html", "d5/d5f/group__group__vision__function__warp__affine" ],
    [ "Warp Perspective", "da/d6a/group__group__vision__function__warp__perspective.html", "da/d6a/group__group__vision__function__warp__perspective" ]
];