var searchData=
[
  ['tablelookup',['TableLookup',['../d5/d4e/group__group__vision__function__lut.html',1,'']]],
  ['thresholding',['Thresholding',['../d3/d1e/group__group__vision__function__threshold.html',1,'']]],
  ['tmp',['tmp',['../dd/de7/group__group__performance.html#a07b019ddbe5e6b1f62c07dd3b2d1c23e',1,'vx_perf_t']]],
  ['tracking_5fstatus',['tracking_status',['../d4/dae/group__group__basic__features.html#a8de67cbadb20013224a749045a491526',1,'vx_keypoint_t']]],
  ['the_20memory_20accessor_20hint_20flags_2e',['The memory accessor hint flags.',['../dc/d26/group__vx__accessor__e.html',1,'']]],
  ['the_20array_20object_20attributes_2e',['The array object attributes.',['../d5/d90/group__vx__array__attribute__e.html',1,'']]],
  ['the_20border_20mode_20list_2e',['The border mode list.',['../db/d1b/group__vx__border__e.html',1,'']]],
  ['the_20unsupported_20border_20mode_20policy_20list_2e',['The unsupported border mode policy list.',['../d0/dec/group__vx__border__policy__e.html',1,'']]],
  ['the_20conversion_20policy_20enumeration_2e',['The Conversion Policy Enumeration.',['../d3/dee/group__vx__convert__policy__e.html',1,'']]],
  ['the_20convolution_20attributes_2e',['The convolution attributes.',['../d5/d1d/group__vx__convolution__attribute__e.html',1,'']]],
  ['the_20distribution_20attribute_20list_2e',['The distribution attribute list.',['../dd/d29/group__vx__distribution__attribute__e.html',1,'']]],
  ['the_20image_20attributes_20constants',['The Image Attributes Constants',['../d0/d7e/group__vx__image__attribute__e.html',1,'']]],
  ['the_20kernel_20attribute_20constants',['The Kernel Attribute Constants',['../d1/d4a/group__vx__kernel__attribute__e.html',1,'']]],
  ['the_20list_20of_20available_20kernels',['The list of available kernels',['../dc/df4/group__vx__kernel__e.html',1,'']]],
  ['the_20list_20of_20available_20libraries',['The list of available libraries',['../db/d3d/group__vx__library__e.html',1,'']]],
  ['the_20look_2dup_20table_20_28lut_29_20attribute_20list_2e',['The Look-Up Table (LUT) attribute list.',['../d3/d31/group__vx__lut__attribute__e.html',1,'']]],
  ['the_20map_2funmap_20flag',['The Map/Unmap flag',['../dd/d9a/group__vx__map__flag__e.html',1,'']]],
  ['the_20matrix_20attributes_2e',['The matrix attributes.',['../d5/d34/group__vx__matrix__attribute__e.html',1,'']]],
  ['the_20meta_20valid_20rectangle_20attributes_2e',['The meta valid rectangle attributes.',['../dc/d7b/group__vx__meta__valid__rect__attribute__e.html',1,'']]],
  ['the_20node_20attribute_20constants',['The Node Attribute Constants',['../d8/d3a/group__vx__node__attribute__e.html',1,'']]],
  ['the_20objectarray_20object_20attributes_2e',['The ObjectArray object attributes.',['../d4/da5/group__vx__object__array__attribute__e.html',1,'']]],
  ['the_20parameter_20attributes_20constants',['The Parameter Attributes Constants',['../d7/daf/group__vx__parameter__attribute__e.html',1,'']]],
  ['the_20parameter_20state_20type_20constants_2e',['The parameter state type constants.',['../d5/d02/group__vx__parameter__state__e.html',1,'']]],
  ['the_20pyramid_20object_20attributes_2e',['The pyramid object attributes.',['../df/da7/group__vx__pyramid__attribute__e.html',1,'']]],
  ['the_20remap_20object_20attributes_2e',['The remap object attributes.',['../d1/d41/group__vx__remap__attribute__e.html',1,'']]],
  ['the_20round_20policy_20enumeration_2e',['The Round Policy Enumeration.',['../d7/d38/group__vx__round__policy__e.html',1,'']]],
  ['the_20scalar_20attributes_20constants',['The Scalar Attributes Constants',['../dd/dd1/group__vx__scalar__attribute__e.html',1,'']]],
  ['the_20vx_5fstatus_20constants',['The vx_status Constants',['../d2/dbd/group__vx__status__e.html',1,'']]],
  ['the_20target_20enumeration_20constants_2e',['The Target Enumeration Constants.',['../da/da3/group__vx__target__e.html',1,'']]],
  ['the_20termination_20criteria_20list_2e',['The termination criteria list.',['../db/d82/group__vx__termination__criteria__e.html',1,'']]],
  ['the_20threshold_20attributes_2e',['The threshold attributes.',['../df/d94/group__vx__threshold__attribute__e.html',1,'']]],
  ['the_20threshold_20types_2e',['The Threshold types.',['../da/d23/group__vx__threshold__type__e.html',1,'']]],
  ['the_20vx_5ftype_20constants',['The VX_TYPE Constants',['../da/d1b/group__vx__type__e.html',1,'']]],
  ['the_20vendor_20id_20list_20for_20openvx_2e',['The Vendor ID list for OpenVX.',['../d6/dc2/group__vx__vendor__id__e.html',1,'']]]
];
